name: release

on:
  push:
    branches:
      - master

    paths-ignore:
      - "**.json"
      - "**.md"

  workflow_dispatch:

jobs:
  pre_run:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ad6cb1b847ffb509a69b745b6ee2f1d14dfe14b8
        with:
          access_token: ${{ github.token }}

  release:
    name: Release
    runs-on: ubuntu-latest

    if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'chore(release): publish')"
    needs:
      - pre_run

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SEMANTIC_RELEASE_PACKAGE: ${{ github.event.repository.name }}
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
